version: '2'

services:
  prometheus:
    image: prom/prometheus
    ports:
    - 9090:9090
    volumes:
    - $PWD/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
    - $PWD/data/grafana_db:/var/lib/grafana grafana/grafana
  consul:
    image:  progrium/consul
    ports:
    - 8400:8400
    - 8500:8500
    - 8600:53/udp
    hostname: node1
    entrypoint:
    - /bin/start
    - -server
    - -bootstrap
    - -ui-dir=/ui
  zipkin:
    image:  openzipkin/zipkin
     ports:
     - 9411:9411